### ISSUE TITLE
Add support for managing loopback devices with Network Manager

### ISSUE THREAD

**Issue by Aethylred** [michaelrigart/ansible-role-interfaces#162]
Network Manager now supports managing and creating loopback devices, can we add support for this feature to the role?

https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/1332

https://access.redhat.com/solutions/2108251

I'll be making a pull request soon as I think this can be done just by modifying the `ethernet_nmconnection.j2` template as only those distributions that will use this template will support this feature.

An example where we're adding a route to the loopback device for a HAproxy  would look like this:

```
interfaces_ether_interfaces:
  - device: lo
    type: loopback
    address: 127.0.0.1
    netmask: 8
    route:
      - table: 100
        device: lo
        network: 0.0.0.0
        netmask: 0
```
