### ISSUE TITLE
[Question] Is it possible to set the default route?

### ISSUE THREAD

**Issue by aanno2** [michaelrigart/ansible-role-interfaces#45]
Is it possible to set the default route?

**Comment by markgoddard** [comment]
Yes - add something like this to an interface:

```
          route:
          - network: 0.0.0.0
            netmask: 0.0.0.0
            gateway: 192.168.1.1
```
