### ISSUE TITLE
[Question] Is it possible to deactive a interface?

### ISSUE THREAD

**Issue by aanno2** [michaelrigart/ansible-role-interfaces#46]
I've got the following:

## 1. I want to setup a bridge with a ethernet (card) enslaved
This is no problem with ansible-role-interfaces, even if the ethernet had the ip addr given to the bridge before the change. Easy peasy.
```
- role: MichaelRigart.interfaces
  interfaces_bridge_interfaces:
    - device: br0
      type: bridge
      bootproto: static
      address: x.x.x.x
      ports: [eth0]
      [...]
```
## 2. I want to go back: deactivate the bridge and assign the ip addr (direct) to the ethernet (card) again
This is possible with ansible-role-interfaces:
```
- role: MichaelRigart.interfaces
  interfaces_ether_interfaces:
    - device: eth0
      bootproto: static
      address: x.x.x.x
      [...]
  interfaces_bridge_interfaces:
    - device: br0
      type: bridge
      bootproto: static
      ports: []
      [...]
```
The `ports: []` is important to remove eth0 from being enslaved. However, this always errors out at the very end with the message:

'Interface br0 is not active'

Well, I guess the bridge has no ip addr (any more), and nothing enslaved, hence `ifup` is not possible. A possible solution to this is to allow something like remove or 'deactive' as an possible explicit state for an interface.
