### ISSUE TITLE
Support managing Infiniband IPoIB interfaces

### ISSUE THREAD

**Issue by milliams** [michaelrigart/ansible-role-interfaces#58]
This role works brilliantly for ethernet interfaces but cannot manage "IP over IB" interfaces. On the whole they should work very similar to the ethernet devices but with a few different options for the network-scripts template.

**Comment by Aethylred** [comment]
I think this is now supported with

```
interfaces_ether_interfaces:
   - device: ib0 
     bootproto: static
     address: 10.41.0.10
     netmask: 255.255.128.0
     type: ipoib
```


https://github.com/michaelrigart/ansible-role-interfaces/issues/76#issuecomment-1096005718
