### ISSUE TITLE
error when changing default gateway to another interface

### ISSUE THREAD

**Issue by pescobar** [michaelrigart/ansible-role-interfaces#59]
I am trying to configure a machine that is working with gateway 10.10.10.1 (eth0) to use a different gateway (100.100.100.254) in eth1 . this is my config:

```
interfaces_ether_interfaces:
  - device: eth0
    bootproto: dhcp
    dnsnameservers: 10.10.10.1
  - device: eth1
    bootproto: static
    address: 100.100.100.66
    netmask: 255.255.255.0
    gateway: 100.100.100.254
```

When I run the role I get this error:

```
RUNNING HANDLER [MichaelRigart.interfaces : Check active Ethernet interface state] ****************************************************************************************************************************************************
skipping: [sosci-devel.scicore-dmz.lan] => (item={u'device': u'eth0', u'dnsnameservers': u'10.10.10.1', u'bootproto': u'dhcp', u'dnssearch': u'scicore-dmz.lan scicore.unibas.ch unibas.ch'})  => {
    "changed": false,
    "item": {
        "bootproto": "dhcp",
        "device": "eth0",
        "dnsnameservers": "10.10.10.1",
       },
    "skip_reason": "Conditional result was False"
}
failed: [sosci-devel.scicore-dmz.lan] (item={u'device': u'eth1', u'netmask': u'255.255.255.0', u'bootproto': u'static', u'gateway': u'100.100.100.254', u'address': u'100.100.100.66'}) => {
    "changed": false,
    "item": {
        "address": "100.100.100.66",
        "bootproto": "static",
        "device": "eth1",
        "gateway": "100.100.100.254",
        "netmask": "255.255.255.0"
    },
    "msg": "Default IPv4 gateway is incorrect"
}
```

If I rerun the role it works fine at the second try.

I could also workaround the issue by commenting out [these lines](https://github.com/michaelrigart/ansible-role-interfaces/blob/master/filter_plugins/filters.py#L89-L95)

any suggestion about how to do a proper fix that could be merged upstream? I can test it and send a PR
