### ISSUE TITLE
Debian bad templates bridge_Debian.j2 : missing trailing newline

### ISSUE THREAD

**Issue by roumano** [michaelrigart/ansible-role-interfaces#84]
If i use the role on a Debian 10 with this data : 
```
    interfaces_bridge_interfaces:
     -  device: br15
        type: bridge
        address: 172.26.15.99
        netmask: 255.255.255.0
        bootproto: static
        stp: "off"
        mtu: 1500
        ports: [eno1]
```

The debug output will be : 
```
TASK [interfaces : Create the network configuration file for bridge devices] *******************************************************************************
changed: [XXX] => (item={'device': 'br15', 'type': 'bridge', 'address': '172.26.15.99', 'netmask': '255.255.255.0', 'bootproto': 'static', 'stp': 'off', 'mtu': 1500, 'ports': ['eno1']})

                "item": {
                    "address": "172.26.15.99",
                    "bootproto": "static",
                    "device": "br15",
                    "mtu": 1500,
                    "netmask": "255.255.255.0",
                    "ports": [
                        "eno1"
                    ],
                    "stp": "off",
                    "type": "bridge"
```

And the destination file will look like this : 
```
auto br15
iface br15 inet static
mtu 1500
address 172.26.15.99
netmask 255.255.255.0
bridge_ports eno1bridge_stp off



```
* the `bridge_stp off` should be on a new line ...
* ideally, we should also remove the 3 empty line at the end of the file
